// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF2glGoZ-50UDCvv1hjVDedwvCtfGnMKE',
    appId: '1:413103151021:web:621aa1a6beef5f3b66f324',
    messagingSenderId: '413103151021',
    projectId: 'login-backend-8e294',
    authDomain: 'login-backend-8e294.firebaseapp.com',
    storageBucket: 'login-backend-8e294.firebasestorage.app',
    measurementId: 'G-ZYLSDGFZ6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl84U7ywQwir0MXXTFtIWGiNSeDqW9ON4',
    appId: '1:413103151021:android:d0e76a655dc589df66f324',
    messagingSenderId: '413103151021',
    projectId: 'login-backend-8e294',
    storageBucket: 'login-backend-8e294.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6PWmbKYj9fBugBsHCenYMm4rb9Fq9lQ4',
    appId: '1:413103151021:ios:800c5ecb7379d56e66f324',
    messagingSenderId: '413103151021',
    projectId: 'login-backend-8e294',
    storageBucket: 'login-backend-8e294.firebasestorage.app',
    iosBundleId: 'com.example.registration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6PWmbKYj9fBugBsHCenYMm4rb9Fq9lQ4',
    appId: '1:413103151021:ios:800c5ecb7379d56e66f324',
    messagingSenderId: '413103151021',
    projectId: 'login-backend-8e294',
    storageBucket: 'login-backend-8e294.firebasestorage.app',
    iosBundleId: 'com.example.registration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF2glGoZ-50UDCvv1hjVDedwvCtfGnMKE',
    appId: '1:413103151021:web:3c80225a29b94ef566f324',
    messagingSenderId: '413103151021',
    projectId: 'login-backend-8e294',
    authDomain: 'login-backend-8e294.firebaseapp.com',
    storageBucket: 'login-backend-8e294.firebasestorage.app',
    measurementId: 'G-RH2J5171FG',
  );
}
